---
- name: install python support
  hosts: vsftpd
  remote_user: root
  strategy: linear
  tasks:
    shell: apt -y install python-dev2.7 python-simplejson

- name: Start vsftpd playbook
  hosts: vsftpd
  strategy: linear

  roles:
    - vsftpd.roles

  vars_files:
    - vsftpd.roles/vars/main.yml
